In [105]:
import numpy as np
import time

# Creating_arrays

In [106]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list1)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [107]:
arr_list1 = np.array(list1)
print(arr_list1)

[ 1  2  3  4  5  6  7  8  9 10]


In [108]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [109]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [110]:
list1 = [1, 2, 3,]
list2 = [6, 7, 8,]
list3 = [11, 12, 13]
arr_list_3 = np.array([[list1, list2, list3]])
print(arr_list_3)

[[[ 1  2  3]
  [ 6  7  8]
  [11 12 13]]]


In [111]:
arr_list_3.ndim # Number of dimensions

3

# Numpy_array_attribites

In [112]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [2, 3, 4], [5, 6, 7]])
arr1.T

array([[1, 4, 2, 5],
       [2, 5, 3, 6],
       [3, 6, 4, 7]])

In [113]:
print(arr1.shape) # Shape of the array
print(arr1.size) # Total number of elements in the array
print(arr1.dtype) # Data type of the elements in the array
print(arr1.itemsize) # Size of each element in bytes
print(arr1.nbytes) # Total size of the array in bytes
print(arr1.T) # Transpose of the array
print(arr1.ndim) # Number of dimensions

(4, 3)
12
int64
8
96
[[1 4 2 5]
 [2 5 3 6]
 [3 6 4 7]]
2


# Creating_3arrays 1d_2d_and_3d_array

In [114]:
ar1 = np.array([1, 2, 3])
print(ar1)
print(ar1.ndim)

[1 2 3]
1


In [115]:
ar1 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar1)
print(ar1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [116]:
lsi1 = [1, 2, 3]
lsi2 = [4, 5, 6]
lsi3 = [7, 8, 9]
arr_lsi3 = np.array([[lsi1], [lsi2], [lsi3]])
print(arr_lsi3)
print(arr_lsi3.ndim)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
3


# Array-initialization_method

In [117]:
# zeros array

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [118]:
# ones array

ones_arr = np.ones((2,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [119]:
# full array

full_arr = np.full((2,3), 5)
print(full_arr)

[[5 5 5]
 [5 5 5]]


In [120]:
# Identity matrix

print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [121]:
# empty array

print(np.empty((2,3)))

[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


In [122]:
# evenly spaced array

print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [123]:
# specified number of equally spaced values between a range
# five equally spaced values between 0 and 10

print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [124]:
# random array - float numbers

print(np.random.rand(2,3))

[[0.33299935 0.11980396 0.35042535]
 [0.70099221 0.12917694 0.66252524]]


In [125]:
# random array - integer numbers

print(np.random.randint(0, 10, (2,3)))

[[1 5 6]
 [6 5 3]]


# Array indexing and slicing

In [126]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [127]:
# indexing

print(a[0]) # Accessing first element
print(a[1]) # Accessing second element
print(a[-1]) # Accessing third element

1
2
3


In [128]:
# Slicing
# array[start:stop:step]
#stop index is exclusive

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(b[0:5]) # Accessing first five elements
 

[1 2 3 4 5]


In [129]:
ba = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(ba[-5:]) # Accessing last five elements

[5 6 7 8 9]


In [130]:
# array[start:stop:step]
print(ba[0:10:2]) # Accessing every second element from the first 10 elements

[1 3 5 7 9]


In [131]:
print(ba[0::2]) # Accessing every second element from the entire array

[1 3 5 7 9]


# Now applying those function on 2d array

In [132]:
cd = np.array([[1, 2, 3], [4, 5, 6]])
print(cd)

[[1 2 3]
 [4 5 6]]


In [133]:
print(np.ndim(cd))

2


In [134]:
print(cd[0:1]) # Accessing the first row

[[1 2 3]]


In [135]:
print(cd[1][2]) # Accessing the element in the second row and third column

6


In [136]:
print(cd[1]) # indexing the second row
print(cd[0:]) # slicing the first row

[4 5 6]
[[1 2 3]
 [4 5 6]]


In [137]:
gh = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(gh)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [138]:
print(gh[1][-1]) # Accessing the first two elements of the second row

6


In [139]:
print(gh[2][-2]) # Accessing the second last element of the third row

8


In [140]:
cv = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(cv)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [141]:
print(cv[1:, 1:]) #slicing the array to access the last two rows and last two columns

[[5 6]
 [8 9]]


In [142]:
print(cv[1][1]) # indexing the element in the second row and second column

5


In [143]:
print(cv[:2, :2]) # slicing the array to access the first row and first column

[[1 2]
 [4 5]]


# Array reshaping and flattening

In [144]:
a1 = np.array([1, 2, 3, 4, 5, 6])
print(a1)

[1 2 3 4 5 6]


In [145]:
reshaped = a1.reshape((6, 1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [146]:
reshape = a1.reshape((2, 3))
print(reshape)

[[1 2 3]
 [4 5 6]]


In [147]:
a1.reshape(6, 1) # Reshaping the array to 3 rows and 2 columns

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [148]:
print(a1.flatten()) # Flattening the array to a 1D array

[1 2 3 4 5 6]


# Array stacking and splitting

In [149]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print(np.vstack((a, b))) # Stacking arrays vertically
print(np.hstack((a, b))) # Stacking arrays horizontally

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [150]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(np.hsplit(c, 3)) # Splitting the array into 3 equal parts horizontally

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [151]:
print(np.vsplit(c, 2)) # Splitting the array into 2 equal parts vertically

[array([[1, 2, 3]]), array([[4, 5, 6]])]


# Mathimatical opration of array

In [152]:
gf = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(gf)

[ 1  2  3  4  5  6  7  8  9 10]


In [153]:
print(gf + 10) # Element-wise addition
print(gf - 10) # Element-wise subtraction
print(gf * 10) # Element-wise multiplication
print(gf / 10) # Element-wise division
print(gf ** 2) # Element-wise exponentiation
print(gf) # Original array remains unchanged

[11 12 13 14 15 16 17 18 19 20]
[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]
[ 10  20  30  40  50  60  70  80  90 100]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[  1   4   9  16  25  36  49  64  81 100]
[ 1  2  3  4  5  6  7  8  9 10]


In [154]:
print(gf ** 0.5) # Element-wise square root

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [155]:
bf = np.array([1, 2, 3, 4])
print(bf)

[1 2 3 4]


In [156]:
print(np.square(bf)) # Element-wise square
print(np.sqrt(bf)) # Element-wise square root

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


# Mathematical opreation on multiple arrays

In [157]:
r = np.array([1, 2, 3, 4])
t = np.array([6, 7, 8, 9])
print(r)
print(t)

[1 2 3 4]
[6 7 8 9]


In [158]:
print(np.add(r, t))
print(np.subtract(r, t))
print(np.multiply(r, t))
print(np.divide(r, t))

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


In [159]:
print(np.dot(r, t)) # multiply corresponding elements and sum the results

80


# Statistical function

In [160]:
l = np.array([[1, 2], [3, 4]])
print(l)

[[1 2]
 [3 4]]


In [161]:
print(np.sum(l)) # Sum of all elements in the array
print(np.median(l)) # Median of all elements in the array
print(np.mean(l)) # Mean of all elements in the array
print(np.std(l)) # Standard deviation of all elements in the array
print(np.mean(l)) # Mean of each column
print(np.max(l)) # Maximum value in the array
print(np.min(l))


10
2.5
2.5
1.118033988749895
2.5
4
1


# Array comparison

In [162]:
q = np.array([2, 4, 6])
w = np.array([3, 5, 6])

print(q)
print(w)

[2 4 6]
[3 5 6]


In [163]:
print(q == w)
print(np.array_equal(q, w)) # Check if two arrays are equal

[False False  True]
False


# Broadcasting

In [164]:
x = np.array([1, 2, 3])
z = np.array([3])

print(x)
print(z)

[1 2 3]
[3]


In [165]:
print(x + z) # Element-wise addition with broadcasting

[4 5 6]


In [166]:
k = np.array([[1, 2, 3], [4, 5, 6]])
j = np.array([[7, 8, 9]])

print(k)
print(j)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [167]:
print(k + j) # Element-wise addition with broadcasting

[[ 8 10 12]
 [11 13 15]]


# Handling with null

In [168]:
data = np.array([1, 2, np.nan, 4, 5, np.inf, 8])
print(data)

[ 1.  2. nan  4.  5. inf  8.]


In [169]:
print(np.isnan(data))

[False False  True False False False False]


In [170]:
print(np.nan_to_num(data))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 5.00000000e+000 1.79769313e+308 8.00000000e+000]


# Save and load array

In [171]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
np.save('my_array.npy', arr) # Save the array to a file

[1 2 3 4 5]


In [172]:
load_arr = np.load('my_array.npy') # Load the array from the file
print(load_arr)

[1 2 3 4 5]
